//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Discounts = new HashSet<Discount>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public string Id_Book { get; set; }
        public Nullable<int> Price { get; set; }
        public string Title { get; set; }
        public string Id_Author { get; set; }
        public string Id_Publisher { get; set; }
        public string Images { get; set; }
        public string Preview { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Condition { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Id_Category { get; set; }
        public Nullable<int> CountView { get; set; }
        public Nullable<System.DateTime> DateExpUpdate { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
